/**
 * Katalog over spill som funker på LAN-tur (linketur).
 * Ren klient-side data — ingen API. Brukes av /linketur.
 */

export type LanMode =
  | "ekte-lan" // Native LAN / direkte IP i spillet
  | "vpn" // Trenger virtuelt LAN (Radmin/ZeroTier/Hamachi)
  | "server" // Trenger egen dedikert server
  | "online"; // Kun online, men fungerer fint samlet i samme rom

export type LanGame = {
  id: string;
  title: string;
  genre: string;
  minPlayers: number;
  maxPlayers: number;
  mode: LanMode;
  /** Kort beskrivelse av oppsettet */
  setup: string;
  /** Mods / hacks / verktøy som utvider spiller-antall eller åpner LAN */
  mods: string[];
  /** Anbefalte maps eller moduser */
  maps: string[];
  /** Kaos-faktor 1-5 — hvor gøy det blir sent på natta */
  chaos: number;
  free?: boolean;
  tags: string[];
};

export const LAN_MODE_LABEL: Record<LanMode, string> = {
  "ekte-lan": "Ekte LAN",
  vpn: "Virtuelt LAN",
  server: "Egen server",
  online: "Online",
};

export const LAN_MODE_COLOR: Record<LanMode, string> = {
  "ekte-lan": "#22c55e",
  vpn: "#38bdf8",
  server: "#a78bfa",
  online: "#f59e0b",
};

export const LAN_TOOLS = [
  {
    name: "Radmin VPN",
    what: "Gratis virtuelt LAN. Alle joiner samme nettverk, spill ser hverandre som lokale.",
    best: "Enkleste løsning når spillet bare har «LAN»-knapp.",
  },
  {
    name: "ZeroTier",
    what: "Moderne mesh-VPN, lav latency, funker også over internett.",
    best: "Når noen deltar hjemmefra.",
  },
  {
    name: "Hamachi",
    what: "Klassikeren. Fungerer, men maks 5 gratis per nettverk.",
    best: "Små grupper / nostalgi.",
  },
  {
    name: "Parsec",
    what: "Deler skjerm + kontroller så flere kan spille på én PC.",
    best: "Couch co-op-spill uten nok maskiner.",
  },
  {
    name: "Nucleus Co-op",
    what: "Splitscreen-hack: kjører flere instanser av samme spill på én PC.",
    best: "Halo MCC, Resident Evil 5, Borderlands.",
  },
  {
    name: "SteamCMD / dedikert server",
    what: "Kjør serveren på en ekstra maskin så alle kan joine uten host-lag.",
    best: "CS2, Minecraft, Valheim, Left 4 Dead 2.",
  },
];

export const LAN_GAMES: LanGame[] = [
  {
    id: "cs2",
    title: "Counter-Strike 2",
    genre: "FPS",
    minPlayers: 2,
    maxPlayers: 10,
    mode: "ekte-lan",
    setup: "Start lokal server med `map de_dust2` og la alle koble til via `connect <ip>` i konsollen.",
    mods: ["SourceMod / Metamod for custom regler", "Retakes-plugin", "1v1 arena-plugin", "Surf/KZ-maps fra Workshop"],
    maps: ["de_dust2", "de_mirage", "de_inferno", "aim_map (oppvarming)"],
    chaos: 3,
    free: true,
    tags: ["klassiker", "kompetitivt", "lagspill"],
  },
  {
    id: "aoe2",
    title: "Age of Empires II: DE",
    genre: "Sanntidsstrategi",
    minPlayers: 2,
    maxPlayers: 8,
    mode: "ekte-lan",
    setup: "Direct LAN-lobby i spillet. Sett opp 4v4 med «Team Together» og delt seier.",
    mods: ["Forgotten Empires-mods", "Small Trees mod (bedre sikt)", "Custom AI (Barbarian)"],
    maps: ["Arabia", "Black Forest", "Nomad", "Michi (turtle-kaos)"],
    chaos: 4,
    tags: ["strategi", "lange kamper"],
  },
  {
    id: "minecraft",
    title: "Minecraft",
    genre: "Sandbox",
    minPlayers: 1,
    maxPlayers: 20,
    mode: "server",
    setup: "Kjør en Paper-server på én maskin, alle joiner via lokal IP. Sett view-distance til 8 for ytelse.",
    mods: ["Bedwars/Skywars-plugins", "Create-modpack", "RLCraft (hardcore)", "Hunger Games-plugin"],
    maps: ["Fersk survival-seed", "Skyblock", "Bedwars-arena", "Parkour-map fra Planet Minecraft"],
    chaos: 3,
    tags: ["kreativt", "alle nivåer"],
  },
  {
    id: "valheim",
    title: "Valheim",
    genre: "Survival co-op",
    minPlayers: 1,
    maxPlayers: 10,
    mode: "server",
    setup: "Dedikert server via SteamCMD med passord. Alle deler samme verden hele turen.",
    mods: ["ValheimPlus (raskere bygging)", "BepInEx", "Better UI"],
    maps: ["Egen seed — bygg base i Meadows", "Boss-run: Eikthyr → Elder"],
    chaos: 2,
    tags: ["co-op", "bygging"],
  },
  {
    id: "l4d2",
    title: "Left 4 Dead 2",
    genre: "Co-op FPS",
    minPlayers: 2,
    maxPlayers: 8,
    mode: "ekte-lan",
    setup: "Konsoll: `sv_lan 1` + `map c1m1_hotel versus`. Versus 4v4 er høydepunktet.",
    mods: ["8+ spillere via Left4Bots/Sourcemod", "Custom kampanjer fra Workshop", "Realism Versus"],
    maps: ["Dark Carnival", "The Parish", "Death Toll", "Custom: Yama"],
    chaos: 5,
    tags: ["zombie", "skriking"],
  },
  {
    id: "warcraft3",
    title: "Warcraft III (Reforged / 1.26)",
    genre: "RTS + custom maps",
    minPlayers: 2,
    maxPlayers: 12,
    mode: "vpn",
    setup: "1.26a med Radmin VPN gir det ekte gamle LAN-følelsen. Custom games i lobbyen.",
    mods: ["DotA Allstars", "Footmen Frenzy", "Island Troll Tribes", "Uther Party"],
    maps: ["DotA 6.83", "Tower Defense (Green TD)", "Vampirism Fire", "Twilight's Eve"],
    chaos: 5,
    tags: ["nostalgi", "custom maps"],
  },
  {
    id: "quake3",
    title: "Quake III Arena",
    genre: "Arena FPS",
    minPlayers: 2,
    maxPlayers: 16,
    mode: "ekte-lan",
    setup: "ioquake3-klienten kjører på alt. Start server, alle joiner lokalt.",
    mods: ["OSP / CPMA", "Rocket Arena 3", "Instagib-mod"],
    maps: ["q3dm17 The Longest Yard", "q3dm6", "q3tourney2"],
    chaos: 4,
    free: true,
    tags: ["retro", "raskt"],
  },
  {
    id: "trackmania",
    title: "TrackMania Nations Forever",
    genre: "Racing",
    minPlayers: 1,
    maxPlayers: 16,
    mode: "ekte-lan",
    setup: "Helt gratis, egen LAN-server innebygd. Perfekt oppvarming for alle.",
    mods: ["Custom map-packs fra TM-Exchange", "Openplanet-plugins"],
    maps: ["Stadium A01-A15", "Rally-pakker", "Nascar-loop maps"],
    chaos: 2,
    free: true,
    tags: ["lett å lære", "alle kan"],
  },
  {
    id: "unrealtournament",
    title: "Unreal Tournament 99 / 2004",
    genre: "Arena FPS",
    minPlayers: 2,
    maxPlayers: 16,
    mode: "ekte-lan",
    setup: "LAN-server direkte i menyen. Onslaught i UT2004 er best med mange.",
    mods: ["Ballistic Weapons", "Instagib+", "Jailbreak"],
    maps: ["DM-Deck16", "CTF-Face", "ONS-Torlan"],
    chaos: 4,
    tags: ["retro", "kaos"],
  },
  {
    id: "stardew",
    title: "Stardew Valley",
    genre: "Farming co-op",
    minPlayers: 1,
    maxPlayers: 8,
    mode: "vpn",
    setup: "Host inviterer via IP. Rolig alternativ til skytespill.",
    mods: ["SMAPI", "Always On Server", "Multiplayer Mod (8+ spillere)"],
    maps: ["Standard farm", "Four Corners (én hjørne per spiller)"],
    chaos: 1,
    tags: ["rolig", "koselig"],
  },
  {
    id: "rocketleague",
    title: "Rocket League",
    genre: "Sport",
    minPlayers: 2,
    maxPlayers: 8,
    mode: "ekte-lan",
    setup: "LAN-match i Epic-klienten (offline LAN-modus) — ingen internett nødvendig.",
    mods: ["BakkesMod", "Rumble/Dropshot-moduser", "Custom training packs"],
    maps: ["DFH Stadium", "Wasteland", "Rocket Labs"],
    chaos: 3,
    tags: ["lett å lære", "lagspill"],
  },
  {
    id: "amongus",
    title: "Among Us",
    genre: "Sosialt bedrag",
    minPlayers: 4,
    maxPlayers: 15,
    mode: "vpn",
    setup: "Local game over samme wifi/VPN — ingen konto trengs.",
    mods: ["Town of Us (nye roller)", "The Other Roles", "Submerged (nytt kart)"],
    maps: ["The Skeld", "Polus", "Airship", "Submerged (mod)"],
    chaos: 5,
    tags: ["fest", "prat"],
  },
  {
    id: "terraria",
    title: "Terraria",
    genre: "Sandbox co-op",
    minPlayers: 1,
    maxPlayers: 16,
    mode: "server",
    setup: "TShock-server på lokal IP. Alle med samme world hele turen.",
    mods: ["Calamity", "tModLoader", "Thorium", "Boss Checklist"],
    maps: ["Ny large world", "Expert mode boss-rush"],
    chaos: 3,
    tags: ["co-op", "bygging"],
  },
  {
    id: "bf1942",
    title: "Battlefield 1942 / Vietnam",
    genre: "Krigs-FPS",
    minPlayers: 4,
    maxPlayers: 32,
    mode: "ekte-lan",
    setup: "Dedikert server-exe fulgte med spillet. Kjempeslag med kjøretøy.",
    mods: ["Desert Combat", "Forgotten Hope", "Galactic Conquest"],
    maps: ["Wake Island", "El Alamein", "Berlin"],
    chaos: 4,
    tags: ["retro", "mange spillere"],
  },
  {
    id: "gmod",
    title: "Garry's Mod",
    genre: "Sandbox / party",
    minPlayers: 2,
    maxPlayers: 16,
    mode: "ekte-lan",
    setup: "`sv_lan 1`, host lokal server og la alle joine via IP.",
    mods: ["TTT (Trouble in Terrorist Town)", "Prop Hunt", "Murder", "DarkRP"],
    maps: ["ttt_minecraftcity", "ph_office", "gm_construct"],
    chaos: 5,
    tags: ["fest", "custom"],
  },
  {
    id: "deeprock",
    title: "Deep Rock Galactic",
    genre: "Co-op FPS",
    minPlayers: 1,
    maxPlayers: 4,
    mode: "online",
    setup: "Lobby med «Friends only». Fungerer perfekt i samme rom.",
    mods: ["Mod.io-mods: flere fiender, custom difficulty"],
    maps: ["Salt Pits", "Glacial Strata", "Deep Dives"],
    chaos: 4,
    tags: ["co-op", "rock and stone"],
  },
  {
    id: "haloMCC",
    title: "Halo: The Master Chief Collection",
    genre: "FPS",
    minPlayers: 2,
    maxPlayers: 16,
    mode: "ekte-lan",
    setup: "Ekte LAN-modus i menyen. Kampanje i co-op eller 4v4 slayer.",
    mods: ["Nucleus Co-op for splitscreen på én PC", "Custom Forge-maps"],
    maps: ["Blood Gulch", "Lockout", "Zanzibar"],
    chaos: 4,
    tags: ["klassiker", "lagspill"],
  },
  {
    id: "openra",
    title: "OpenRA (Red Alert / C&C)",
    genre: "Sanntidsstrategi",
    minPlayers: 2,
    maxPlayers: 8,
    mode: "ekte-lan",
    setup: "Gratis, moderne remake med innebygd LAN-lobby.",
    mods: ["Red Alert", "Tiberian Dawn", "Dune 2000"],
    maps: ["A Path Beyond", "Ore Gardens", "Behind the Veil"],
    chaos: 3,
    free: true,
    tags: ["retro", "strategi"],
  },
  {
    id: "0ad",
    title: "0 A.D.",
    genre: "Sanntidsstrategi",
    minPlayers: 2,
    maxPlayers: 8,
    mode: "ekte-lan",
    setup: "Helt gratis og open source. LAN-lobby rett i spillet.",
    mods: ["Delenda Est", "Autociv (bedre UI)"],
    maps: ["Mainland", "Danubius", "Corinthian Isthmus"],
    chaos: 2,
    free: true,
    tags: ["gratis", "strategi"],
  },
  {
    id: "teeworlds",
    title: "Teeworlds / DDNet",
    genre: "2D arena",
    minPlayers: 2,
    maxPlayers: 16,
    mode: "ekte-lan",
    setup: "Bittelitt nedlasting, kjører på hva som helst. Egen lokal server på sekunder.",
    mods: ["DDRace co-op-baner", "Instagib", "CTF-mods"],
    maps: ["ctf1", "dm1", "DDNet Novice-baner"],
    chaos: 4,
    free: true,
    tags: ["gratis", "lett å kjøre"],
  },
  {
    id: "jackbox",
    title: "Jackbox Party Pack",
    genre: "Partyspill",
    minPlayers: 3,
    maxPlayers: 10,
    mode: "online",
    setup: "Én PC på TV/projektor, alle andre bruker mobilen. Null installasjon for gjestene.",
    mods: ["Ingen — men bruk «Extended Timers» for fyllekalde hjerner"],
    maps: ["Quiplash", "Fibbage", "Trivia Murder Party"],
    chaos: 5,
    tags: ["fest", "alle kan", "pause"],
  },
  {
    id: "supertuxkart",
    title: "SuperTuxKart",
    genre: "Racing",
    minPlayers: 1,
    maxPlayers: 8,
    mode: "ekte-lan",
    setup: "Gratis Mario Kart-alternativ med innebygd LAN-server.",
    mods: ["Add-on tracks fra STK-portalen"],
    maps: ["Black Forest", "Cocoa Temple", "Battle: Icy Soccer Field"],
    chaos: 3,
    free: true,
    tags: ["gratis", "alle kan"],
  },
  {
    id: "rimworld-mp",
    title: "RimWorld (Multiplayer-mod)",
    genre: "Kolonisim",
    minPlayers: 2,
    maxPlayers: 6,
    mode: "vpn",
    setup: "Zetrith's Multiplayer-mod gjør singleplayer-spillet til co-op over LAN.",
    mods: ["Zetrith Multiplayer", "Hospitality", "Vanilla Expanded"],
    maps: ["Delt koloni", "Én koloni per spiller på samme kart"],
    chaos: 2,
    tags: ["mod-drevet", "lange kamper"],
  },
  {
    id: "borderlands3",
    title: "Borderlands 2 / 3",
    genre: "Loot-shooter co-op",
    minPlayers: 1,
    maxPlayers: 4,
    mode: "ekte-lan",
    setup: "BL2 har ekte LAN-modus. BL3 kjøres via invite, evt. Nucleus Co-op for splitscreen.",
    mods: ["UCP (Unofficial Community Patch)", "Nucleus Co-op", "Reborn-modpack"],
    maps: ["Kampanje fra start", "Circle of Slaughter", "Raid-bosser"],
    chaos: 3,
    tags: ["co-op", "loot"],
  },
];

export const ALL_GENRES = Array.from(new Set(LAN_GAMES.map((g) => g.genre))).sort();
