/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YtelseRouteImport } from './routes/ytelse'
import { Route as VarmeRouteImport } from './routes/varme'
import { Route as VarkartRouteImport } from './routes/varkart'
import { Route as VarfavoritterRouteImport } from './routes/varfavoritter'
import { Route as VarRouteImport } from './routes/var'
import { Route as VakttarnetRouteImport } from './routes/vakttarnet'
import { Route as UtlanRouteImport } from './routes/utlan'
import { Route as TreningRouteImport } from './routes/trening'
import { Route as StromkronikenRouteImport } from './routes/stromkroniken'
import { Route as StovsugerenRouteImport } from './routes/stovsugeren'
import { Route as Steintavle2RouteImport } from './routes/steintavle-2'
import { Route as SteintavleRouteImport } from './routes/steintavle'
import { Route as SmarthusRouteImport } from './routes/smarthus'
import { Route as SmartDashbordRouteImport } from './routes/smart-dashbord'
import { Route as SkatteUtregningenRouteImport } from './routes/skatte-utregningen'
import { Route as RoborockRouteImport } from './routes/roborock'
import { Route as RegnskapRouteImport } from './routes/regnskap'
import { Route as PushVarslingerRouteImport } from './routes/push-varslinger'
import { Route as PollenRouteImport } from './routes/pollen'
import { Route as LysRouteImport } from './routes/lys'
import { Route as LinketurRouteImport } from './routes/linketur'
import { Route as KvitteringerRouteImport } from './routes/kvitteringer'
import { Route as KostholdRouteImport } from './routes/kosthold'
import { Route as JaguarRouteImport } from './routes/jaguar'
import { Route as IphoneAppRouteImport } from './routes/iphone-app'
import { Route as HyttaRouteImport } from './routes/hytta'
import { Route as GressklipperRouteImport } from './routes/gressklipper'
import { Route as BudsjettRouteImport } from './routes/budsjett'
import { Route as BruksanvisningRouteImport } from './routes/bruksanvisning'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksLogPulseRouteImport } from './routes/hooks.log-pulse'
import { Route as ApiStravaStartRouteImport } from './routes/api.strava.start'
import { Route as ApiStravaCallbackRouteImport } from './routes/api.strava.callback'
import { Route as ApiHomeyStartRouteImport } from './routes/api.homey.start'
import { Route as ApiHomeyCallbackRouteImport } from './routes/api.homey.callback'
import { Route as ApiPublicHooksVocPollRouteImport } from './routes/api/public/hooks/voc-poll'
import { Route as ApiPublicHooksStravaPollRouteImport } from './routes/api/public/hooks/strava-poll'
import { Route as ApiPublicHooksSnapshotTibberDailyRouteImport } from './routes/api.public.hooks.snapshot-tibber-daily'
import { Route as ApiPublicHooksSnapshotPulseRouteImport } from './routes/api.public.hooks.snapshot-pulse'
import { Route as ApiPublicHooksRadonPollRouteImport } from './routes/api/public/hooks/radon-poll'
import { Route as ApiPublicHooksOpenMeteoWarmRouteImport } from './routes/api/public/hooks/open-meteo-warm'
import { Route as ApiPublicHooksNetatmoClimateRefreshRouteImport } from './routes/api/public/hooks/netatmo-climate-refresh'
import { Route as ApiPublicHooksHomeySensorPollRouteImport } from './routes/api/public/hooks/homey-sensor-poll'
import { Route as ApiPublicHooksGardenaPollRouteImport } from './routes/api/public/hooks/gardena-poll'
import { Route as ApiPublicHooksEufyPollRouteImport } from './routes/api/public/hooks/eufy-poll'
import { Route as ApiPublicHooksEufyRouteImport } from './routes/api/public/hooks/eufy'
import { Route as ApiPublicHooksBackfillPbthHistoryRouteImport } from './routes/api.public.hooks.backfill-pbth-history'
import { Route as ApiPublicHooksAirQualityHistoryDailyRouteImport } from './routes/api/public/hooks/air-quality-history-daily'
import { Route as ApiPublicHooksAgendaPushRouteImport } from './routes/api.public.hooks.agenda-push'

const YtelseRoute = YtelseRouteImport.update({
  id: '/ytelse',
  path: '/ytelse',
  getParentRoute: () => rootRouteImport,
} as any)
const VarmeRoute = VarmeRouteImport.update({
  id: '/varme',
  path: '/varme',
  getParentRoute: () => rootRouteImport,
} as any)
const VarkartRoute = VarkartRouteImport.update({
  id: '/varkart',
  path: '/varkart',
  getParentRoute: () => rootRouteImport,
} as any)
const VarfavoritterRoute = VarfavoritterRouteImport.update({
  id: '/varfavoritter',
  path: '/varfavoritter',
  getParentRoute: () => rootRouteImport,
} as any)
const VarRoute = VarRouteImport.update({
  id: '/var',
  path: '/var',
  getParentRoute: () => rootRouteImport,
} as any)
const VakttarnetRoute = VakttarnetRouteImport.update({
  id: '/vakttarnet',
  path: '/vakttarnet',
  getParentRoute: () => rootRouteImport,
} as any)
const UtlanRoute = UtlanRouteImport.update({
  id: '/utlan',
  path: '/utlan',
  getParentRoute: () => rootRouteImport,
} as any)
const TreningRoute = TreningRouteImport.update({
  id: '/trening',
  path: '/trening',
  getParentRoute: () => rootRouteImport,
} as any)
const StromkronikenRoute = StromkronikenRouteImport.update({
  id: '/stromkroniken',
  path: '/stromkroniken',
  getParentRoute: () => rootRouteImport,
} as any)
const StovsugerenRoute = StovsugerenRouteImport.update({
  id: '/stovsugeren',
  path: '/stovsugeren',
  getParentRoute: () => rootRouteImport,
} as any)
const Steintavle2Route = Steintavle2RouteImport.update({
  id: '/steintavle-2',
  path: '/steintavle-2',
  getParentRoute: () => rootRouteImport,
} as any)
const SteintavleRoute = SteintavleRouteImport.update({
  id: '/steintavle',
  path: '/steintavle',
  getParentRoute: () => rootRouteImport,
} as any)
const SmarthusRoute = SmarthusRouteImport.update({
  id: '/smarthus',
  path: '/smarthus',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartDashbordRoute = SmartDashbordRouteImport.update({
  id: '/smart-dashbord',
  path: '/smart-dashbord',
  getParentRoute: () => rootRouteImport,
} as any)
const SkatteUtregningenRoute = SkatteUtregningenRouteImport.update({
  id: '/skatte-utregningen',
  path: '/skatte-utregningen',
  getParentRoute: () => rootRouteImport,
} as any)
const RoborockRoute = RoborockRouteImport.update({
  id: '/roborock',
  path: '/roborock',
  getParentRoute: () => rootRouteImport,
} as any)
const RegnskapRoute = RegnskapRouteImport.update({
  id: '/regnskap',
  path: '/regnskap',
  getParentRoute: () => rootRouteImport,
} as any)
const PushVarslingerRoute = PushVarslingerRouteImport.update({
  id: '/push-varslinger',
  path: '/push-varslinger',
  getParentRoute: () => rootRouteImport,
} as any)
const PollenRoute = PollenRouteImport.update({
  id: '/pollen',
  path: '/pollen',
  getParentRoute: () => rootRouteImport,
} as any)
const LysRoute = LysRouteImport.update({
  id: '/lys',
  path: '/lys',
  getParentRoute: () => rootRouteImport,
} as any)
const LinketurRoute = LinketurRouteImport.update({
  id: '/linketur',
  path: '/linketur',
  getParentRoute: () => rootRouteImport,
} as any)
const KvitteringerRoute = KvitteringerRouteImport.update({
  id: '/kvitteringer',
  path: '/kvitteringer',
  getParentRoute: () => rootRouteImport,
} as any)
const KostholdRoute = KostholdRouteImport.update({
  id: '/kosthold',
  path: '/kosthold',
  getParentRoute: () => rootRouteImport,
} as any)
const JaguarRoute = JaguarRouteImport.update({
  id: '/jaguar',
  path: '/jaguar',
  getParentRoute: () => rootRouteImport,
} as any)
const IphoneAppRoute = IphoneAppRouteImport.update({
  id: '/iphone-app',
  path: '/iphone-app',
  getParentRoute: () => rootRouteImport,
} as any)
const HyttaRoute = HyttaRouteImport.update({
  id: '/hytta',
  path: '/hytta',
  getParentRoute: () => rootRouteImport,
} as any)
const GressklipperRoute = GressklipperRouteImport.update({
  id: '/gressklipper',
  path: '/gressklipper',
  getParentRoute: () => rootRouteImport,
} as any)
const BudsjettRoute = BudsjettRouteImport.update({
  id: '/budsjett',
  path: '/budsjett',
  getParentRoute: () => rootRouteImport,
} as any)
const BruksanvisningRoute = BruksanvisningRouteImport.update({
  id: '/bruksanvisning',
  path: '/bruksanvisning',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksLogPulseRoute = HooksLogPulseRouteImport.update({
  id: '/hooks/log-pulse',
  path: '/hooks/log-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaStartRoute = ApiStravaStartRouteImport.update({
  id: '/api/strava/start',
  path: '/api/strava/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaCallbackRoute = ApiStravaCallbackRouteImport.update({
  id: '/api/strava/callback',
  path: '/api/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeyStartRoute = ApiHomeyStartRouteImport.update({
  id: '/api/homey/start',
  path: '/api/homey/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeyCallbackRoute = ApiHomeyCallbackRouteImport.update({
  id: '/api/homey/callback',
  path: '/api/homey/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksVocPollRoute = ApiPublicHooksVocPollRouteImport.update({
  id: '/api/public/hooks/voc-poll',
  path: '/api/public/hooks/voc-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksStravaPollRoute =
  ApiPublicHooksStravaPollRouteImport.update({
    id: '/api/public/hooks/strava-poll',
    path: '/api/public/hooks/strava-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSnapshotTibberDailyRoute =
  ApiPublicHooksSnapshotTibberDailyRouteImport.update({
    id: '/api/public/hooks/snapshot-tibber-daily',
    path: '/api/public/hooks/snapshot-tibber-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSnapshotPulseRoute =
  ApiPublicHooksSnapshotPulseRouteImport.update({
    id: '/api/public/hooks/snapshot-pulse',
    path: '/api/public/hooks/snapshot-pulse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRadonPollRoute = ApiPublicHooksRadonPollRouteImport.update({
  id: '/api/public/hooks/radon-poll',
  path: '/api/public/hooks/radon-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksOpenMeteoWarmRoute =
  ApiPublicHooksOpenMeteoWarmRouteImport.update({
    id: '/api/public/hooks/open-meteo-warm',
    path: '/api/public/hooks/open-meteo-warm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNetatmoClimateRefreshRoute =
  ApiPublicHooksNetatmoClimateRefreshRouteImport.update({
    id: '/api/public/hooks/netatmo-climate-refresh',
    path: '/api/public/hooks/netatmo-climate-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHomeySensorPollRoute =
  ApiPublicHooksHomeySensorPollRouteImport.update({
    id: '/api/public/hooks/homey-sensor-poll',
    path: '/api/public/hooks/homey-sensor-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGardenaPollRoute =
  ApiPublicHooksGardenaPollRouteImport.update({
    id: '/api/public/hooks/gardena-poll',
    path: '/api/public/hooks/gardena-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEufyPollRoute = ApiPublicHooksEufyPollRouteImport.update({
  id: '/api/public/hooks/eufy-poll',
  path: '/api/public/hooks/eufy-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEufyRoute = ApiPublicHooksEufyRouteImport.update({
  id: '/api/public/hooks/eufy',
  path: '/api/public/hooks/eufy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBackfillPbthHistoryRoute =
  ApiPublicHooksBackfillPbthHistoryRouteImport.update({
    id: '/api/public/hooks/backfill-pbth-history',
    path: '/api/public/hooks/backfill-pbth-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAirQualityHistoryDailyRoute =
  ApiPublicHooksAirQualityHistoryDailyRouteImport.update({
    id: '/api/public/hooks/air-quality-history-daily',
    path: '/api/public/hooks/air-quality-history-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgendaPushRoute =
  ApiPublicHooksAgendaPushRouteImport.update({
    id: '/api/public/hooks/agenda-push',
    path: '/api/public/hooks/agenda-push',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/bruksanvisning': typeof BruksanvisningRoute
  '/budsjett': typeof BudsjettRoute
  '/gressklipper': typeof GressklipperRoute
  '/hytta': typeof HyttaRoute
  '/iphone-app': typeof IphoneAppRoute
  '/jaguar': typeof JaguarRoute
  '/kosthold': typeof KostholdRoute
  '/kvitteringer': typeof KvitteringerRoute
  '/linketur': typeof LinketurRoute
  '/lys': typeof LysRoute
  '/pollen': typeof PollenRoute
  '/push-varslinger': typeof PushVarslingerRoute
  '/regnskap': typeof RegnskapRoute
  '/roborock': typeof RoborockRoute
  '/skatte-utregningen': typeof SkatteUtregningenRoute
  '/smart-dashbord': typeof SmartDashbordRoute
  '/smarthus': typeof SmarthusRoute
  '/steintavle': typeof SteintavleRoute
  '/steintavle-2': typeof Steintavle2Route
  '/stovsugeren': typeof StovsugerenRoute
  '/stromkroniken': typeof StromkronikenRoute
  '/trening': typeof TreningRoute
  '/utlan': typeof UtlanRoute
  '/vakttarnet': typeof VakttarnetRoute
  '/var': typeof VarRoute
  '/varfavoritter': typeof VarfavoritterRoute
  '/varkart': typeof VarkartRoute
  '/varme': typeof VarmeRoute
  '/ytelse': typeof YtelseRoute
  '/hooks/log-pulse': typeof HooksLogPulseRoute
  '/api/homey/callback': typeof ApiHomeyCallbackRoute
  '/api/homey/start': typeof ApiHomeyStartRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/strava/start': typeof ApiStravaStartRoute
  '/api/public/hooks/agenda-push': typeof ApiPublicHooksAgendaPushRoute
  '/api/public/hooks/air-quality-history-daily': typeof ApiPublicHooksAirQualityHistoryDailyRoute
  '/api/public/hooks/backfill-pbth-history': typeof ApiPublicHooksBackfillPbthHistoryRoute
  '/api/public/hooks/eufy': typeof ApiPublicHooksEufyRoute
  '/api/public/hooks/eufy-poll': typeof ApiPublicHooksEufyPollRoute
  '/api/public/hooks/gardena-poll': typeof ApiPublicHooksGardenaPollRoute
  '/api/public/hooks/homey-sensor-poll': typeof ApiPublicHooksHomeySensorPollRoute
  '/api/public/hooks/netatmo-climate-refresh': typeof ApiPublicHooksNetatmoClimateRefreshRoute
  '/api/public/hooks/open-meteo-warm': typeof ApiPublicHooksOpenMeteoWarmRoute
  '/api/public/hooks/radon-poll': typeof ApiPublicHooksRadonPollRoute
  '/api/public/hooks/snapshot-pulse': typeof ApiPublicHooksSnapshotPulseRoute
  '/api/public/hooks/snapshot-tibber-daily': typeof ApiPublicHooksSnapshotTibberDailyRoute
  '/api/public/hooks/strava-poll': typeof ApiPublicHooksStravaPollRoute
  '/api/public/hooks/voc-poll': typeof ApiPublicHooksVocPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/bruksanvisning': typeof BruksanvisningRoute
  '/budsjett': typeof BudsjettRoute
  '/gressklipper': typeof GressklipperRoute
  '/hytta': typeof HyttaRoute
  '/iphone-app': typeof IphoneAppRoute
  '/jaguar': typeof JaguarRoute
  '/kosthold': typeof KostholdRoute
  '/kvitteringer': typeof KvitteringerRoute
  '/linketur': typeof LinketurRoute
  '/lys': typeof LysRoute
  '/pollen': typeof PollenRoute
  '/push-varslinger': typeof PushVarslingerRoute
  '/regnskap': typeof RegnskapRoute
  '/roborock': typeof RoborockRoute
  '/skatte-utregningen': typeof SkatteUtregningenRoute
  '/smart-dashbord': typeof SmartDashbordRoute
  '/smarthus': typeof SmarthusRoute
  '/steintavle': typeof SteintavleRoute
  '/steintavle-2': typeof Steintavle2Route
  '/stovsugeren': typeof StovsugerenRoute
  '/stromkroniken': typeof StromkronikenRoute
  '/trening': typeof TreningRoute
  '/utlan': typeof UtlanRoute
  '/vakttarnet': typeof VakttarnetRoute
  '/var': typeof VarRoute
  '/varfavoritter': typeof VarfavoritterRoute
  '/varkart': typeof VarkartRoute
  '/varme': typeof VarmeRoute
  '/ytelse': typeof YtelseRoute
  '/hooks/log-pulse': typeof HooksLogPulseRoute
  '/api/homey/callback': typeof ApiHomeyCallbackRoute
  '/api/homey/start': typeof ApiHomeyStartRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/strava/start': typeof ApiStravaStartRoute
  '/api/public/hooks/agenda-push': typeof ApiPublicHooksAgendaPushRoute
  '/api/public/hooks/air-quality-history-daily': typeof ApiPublicHooksAirQualityHistoryDailyRoute
  '/api/public/hooks/backfill-pbth-history': typeof ApiPublicHooksBackfillPbthHistoryRoute
  '/api/public/hooks/eufy': typeof ApiPublicHooksEufyRoute
  '/api/public/hooks/eufy-poll': typeof ApiPublicHooksEufyPollRoute
  '/api/public/hooks/gardena-poll': typeof ApiPublicHooksGardenaPollRoute
  '/api/public/hooks/homey-sensor-poll': typeof ApiPublicHooksHomeySensorPollRoute
  '/api/public/hooks/netatmo-climate-refresh': typeof ApiPublicHooksNetatmoClimateRefreshRoute
  '/api/public/hooks/open-meteo-warm': typeof ApiPublicHooksOpenMeteoWarmRoute
  '/api/public/hooks/radon-poll': typeof ApiPublicHooksRadonPollRoute
  '/api/public/hooks/snapshot-pulse': typeof ApiPublicHooksSnapshotPulseRoute
  '/api/public/hooks/snapshot-tibber-daily': typeof ApiPublicHooksSnapshotTibberDailyRoute
  '/api/public/hooks/strava-poll': typeof ApiPublicHooksStravaPollRoute
  '/api/public/hooks/voc-poll': typeof ApiPublicHooksVocPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/bruksanvisning': typeof BruksanvisningRoute
  '/budsjett': typeof BudsjettRoute
  '/gressklipper': typeof GressklipperRoute
  '/hytta': typeof HyttaRoute
  '/iphone-app': typeof IphoneAppRoute
  '/jaguar': typeof JaguarRoute
  '/kosthold': typeof KostholdRoute
  '/kvitteringer': typeof KvitteringerRoute
  '/linketur': typeof LinketurRoute
  '/lys': typeof LysRoute
  '/pollen': typeof PollenRoute
  '/push-varslinger': typeof PushVarslingerRoute
  '/regnskap': typeof RegnskapRoute
  '/roborock': typeof RoborockRoute
  '/skatte-utregningen': typeof SkatteUtregningenRoute
  '/smart-dashbord': typeof SmartDashbordRoute
  '/smarthus': typeof SmarthusRoute
  '/steintavle': typeof SteintavleRoute
  '/steintavle-2': typeof Steintavle2Route
  '/stovsugeren': typeof StovsugerenRoute
  '/stromkroniken': typeof StromkronikenRoute
  '/trening': typeof TreningRoute
  '/utlan': typeof UtlanRoute
  '/vakttarnet': typeof VakttarnetRoute
  '/var': typeof VarRoute
  '/varfavoritter': typeof VarfavoritterRoute
  '/varkart': typeof VarkartRoute
  '/varme': typeof VarmeRoute
  '/ytelse': typeof YtelseRoute
  '/hooks/log-pulse': typeof HooksLogPulseRoute
  '/api/homey/callback': typeof ApiHomeyCallbackRoute
  '/api/homey/start': typeof ApiHomeyStartRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/strava/start': typeof ApiStravaStartRoute
  '/api/public/hooks/agenda-push': typeof ApiPublicHooksAgendaPushRoute
  '/api/public/hooks/air-quality-history-daily': typeof ApiPublicHooksAirQualityHistoryDailyRoute
  '/api/public/hooks/backfill-pbth-history': typeof ApiPublicHooksBackfillPbthHistoryRoute
  '/api/public/hooks/eufy': typeof ApiPublicHooksEufyRoute
  '/api/public/hooks/eufy-poll': typeof ApiPublicHooksEufyPollRoute
  '/api/public/hooks/gardena-poll': typeof ApiPublicHooksGardenaPollRoute
  '/api/public/hooks/homey-sensor-poll': typeof ApiPublicHooksHomeySensorPollRoute
  '/api/public/hooks/netatmo-climate-refresh': typeof ApiPublicHooksNetatmoClimateRefreshRoute
  '/api/public/hooks/open-meteo-warm': typeof ApiPublicHooksOpenMeteoWarmRoute
  '/api/public/hooks/radon-poll': typeof ApiPublicHooksRadonPollRoute
  '/api/public/hooks/snapshot-pulse': typeof ApiPublicHooksSnapshotPulseRoute
  '/api/public/hooks/snapshot-tibber-daily': typeof ApiPublicHooksSnapshotTibberDailyRoute
  '/api/public/hooks/strava-poll': typeof ApiPublicHooksStravaPollRoute
  '/api/public/hooks/voc-poll': typeof ApiPublicHooksVocPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/bruksanvisning'
    | '/budsjett'
    | '/gressklipper'
    | '/hytta'
    | '/iphone-app'
    | '/jaguar'
    | '/kosthold'
    | '/kvitteringer'
    | '/linketur'
    | '/lys'
    | '/pollen'
    | '/push-varslinger'
    | '/regnskap'
    | '/roborock'
    | '/skatte-utregningen'
    | '/smart-dashbord'
    | '/smarthus'
    | '/steintavle'
    | '/steintavle-2'
    | '/stovsugeren'
    | '/stromkroniken'
    | '/trening'
    | '/utlan'
    | '/vakttarnet'
    | '/var'
    | '/varfavoritter'
    | '/varkart'
    | '/varme'
    | '/ytelse'
    | '/hooks/log-pulse'
    | '/api/homey/callback'
    | '/api/homey/start'
    | '/api/strava/callback'
    | '/api/strava/start'
    | '/api/public/hooks/agenda-push'
    | '/api/public/hooks/air-quality-history-daily'
    | '/api/public/hooks/backfill-pbth-history'
    | '/api/public/hooks/eufy'
    | '/api/public/hooks/eufy-poll'
    | '/api/public/hooks/gardena-poll'
    | '/api/public/hooks/homey-sensor-poll'
    | '/api/public/hooks/netatmo-climate-refresh'
    | '/api/public/hooks/open-meteo-warm'
    | '/api/public/hooks/radon-poll'
    | '/api/public/hooks/snapshot-pulse'
    | '/api/public/hooks/snapshot-tibber-daily'
    | '/api/public/hooks/strava-poll'
    | '/api/public/hooks/voc-poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/bruksanvisning'
    | '/budsjett'
    | '/gressklipper'
    | '/hytta'
    | '/iphone-app'
    | '/jaguar'
    | '/kosthold'
    | '/kvitteringer'
    | '/linketur'
    | '/lys'
    | '/pollen'
    | '/push-varslinger'
    | '/regnskap'
    | '/roborock'
    | '/skatte-utregningen'
    | '/smart-dashbord'
    | '/smarthus'
    | '/steintavle'
    | '/steintavle-2'
    | '/stovsugeren'
    | '/stromkroniken'
    | '/trening'
    | '/utlan'
    | '/vakttarnet'
    | '/var'
    | '/varfavoritter'
    | '/varkart'
    | '/varme'
    | '/ytelse'
    | '/hooks/log-pulse'
    | '/api/homey/callback'
    | '/api/homey/start'
    | '/api/strava/callback'
    | '/api/strava/start'
    | '/api/public/hooks/agenda-push'
    | '/api/public/hooks/air-quality-history-daily'
    | '/api/public/hooks/backfill-pbth-history'
    | '/api/public/hooks/eufy'
    | '/api/public/hooks/eufy-poll'
    | '/api/public/hooks/gardena-poll'
    | '/api/public/hooks/homey-sensor-poll'
    | '/api/public/hooks/netatmo-climate-refresh'
    | '/api/public/hooks/open-meteo-warm'
    | '/api/public/hooks/radon-poll'
    | '/api/public/hooks/snapshot-pulse'
    | '/api/public/hooks/snapshot-tibber-daily'
    | '/api/public/hooks/strava-poll'
    | '/api/public/hooks/voc-poll'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/bruksanvisning'
    | '/budsjett'
    | '/gressklipper'
    | '/hytta'
    | '/iphone-app'
    | '/jaguar'
    | '/kosthold'
    | '/kvitteringer'
    | '/linketur'
    | '/lys'
    | '/pollen'
    | '/push-varslinger'
    | '/regnskap'
    | '/roborock'
    | '/skatte-utregningen'
    | '/smart-dashbord'
    | '/smarthus'
    | '/steintavle'
    | '/steintavle-2'
    | '/stovsugeren'
    | '/stromkroniken'
    | '/trening'
    | '/utlan'
    | '/vakttarnet'
    | '/var'
    | '/varfavoritter'
    | '/varkart'
    | '/varme'
    | '/ytelse'
    | '/hooks/log-pulse'
    | '/api/homey/callback'
    | '/api/homey/start'
    | '/api/strava/callback'
    | '/api/strava/start'
    | '/api/public/hooks/agenda-push'
    | '/api/public/hooks/air-quality-history-daily'
    | '/api/public/hooks/backfill-pbth-history'
    | '/api/public/hooks/eufy'
    | '/api/public/hooks/eufy-poll'
    | '/api/public/hooks/gardena-poll'
    | '/api/public/hooks/homey-sensor-poll'
    | '/api/public/hooks/netatmo-climate-refresh'
    | '/api/public/hooks/open-meteo-warm'
    | '/api/public/hooks/radon-poll'
    | '/api/public/hooks/snapshot-pulse'
    | '/api/public/hooks/snapshot-tibber-daily'
    | '/api/public/hooks/strava-poll'
    | '/api/public/hooks/voc-poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  BruksanvisningRoute: typeof BruksanvisningRoute
  BudsjettRoute: typeof BudsjettRoute
  GressklipperRoute: typeof GressklipperRoute
  HyttaRoute: typeof HyttaRoute
  IphoneAppRoute: typeof IphoneAppRoute
  JaguarRoute: typeof JaguarRoute
  KostholdRoute: typeof KostholdRoute
  KvitteringerRoute: typeof KvitteringerRoute
  LinketurRoute: typeof LinketurRoute
  LysRoute: typeof LysRoute
  PollenRoute: typeof PollenRoute
  PushVarslingerRoute: typeof PushVarslingerRoute
  RegnskapRoute: typeof RegnskapRoute
  RoborockRoute: typeof RoborockRoute
  SkatteUtregningenRoute: typeof SkatteUtregningenRoute
  SmartDashbordRoute: typeof SmartDashbordRoute
  SmarthusRoute: typeof SmarthusRoute
  SteintavleRoute: typeof SteintavleRoute
  Steintavle2Route: typeof Steintavle2Route
  StovsugerenRoute: typeof StovsugerenRoute
  StromkronikenRoute: typeof StromkronikenRoute
  TreningRoute: typeof TreningRoute
  UtlanRoute: typeof UtlanRoute
  VakttarnetRoute: typeof VakttarnetRoute
  VarRoute: typeof VarRoute
  VarfavoritterRoute: typeof VarfavoritterRoute
  VarkartRoute: typeof VarkartRoute
  VarmeRoute: typeof VarmeRoute
  YtelseRoute: typeof YtelseRoute
  HooksLogPulseRoute: typeof HooksLogPulseRoute
  ApiHomeyCallbackRoute: typeof ApiHomeyCallbackRoute
  ApiHomeyStartRoute: typeof ApiHomeyStartRoute
  ApiStravaCallbackRoute: typeof ApiStravaCallbackRoute
  ApiStravaStartRoute: typeof ApiStravaStartRoute
  ApiPublicHooksAgendaPushRoute: typeof ApiPublicHooksAgendaPushRoute
  ApiPublicHooksAirQualityHistoryDailyRoute: typeof ApiPublicHooksAirQualityHistoryDailyRoute
  ApiPublicHooksBackfillPbthHistoryRoute: typeof ApiPublicHooksBackfillPbthHistoryRoute
  ApiPublicHooksEufyRoute: typeof ApiPublicHooksEufyRoute
  ApiPublicHooksEufyPollRoute: typeof ApiPublicHooksEufyPollRoute
  ApiPublicHooksGardenaPollRoute: typeof ApiPublicHooksGardenaPollRoute
  ApiPublicHooksHomeySensorPollRoute: typeof ApiPublicHooksHomeySensorPollRoute
  ApiPublicHooksNetatmoClimateRefreshRoute: typeof ApiPublicHooksNetatmoClimateRefreshRoute
  ApiPublicHooksOpenMeteoWarmRoute: typeof ApiPublicHooksOpenMeteoWarmRoute
  ApiPublicHooksRadonPollRoute: typeof ApiPublicHooksRadonPollRoute
  ApiPublicHooksSnapshotPulseRoute: typeof ApiPublicHooksSnapshotPulseRoute
  ApiPublicHooksSnapshotTibberDailyRoute: typeof ApiPublicHooksSnapshotTibberDailyRoute
  ApiPublicHooksStravaPollRoute: typeof ApiPublicHooksStravaPollRoute
  ApiPublicHooksVocPollRoute: typeof ApiPublicHooksVocPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ytelse': {
      id: '/ytelse'
      path: '/ytelse'
      fullPath: '/ytelse'
      preLoaderRoute: typeof YtelseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varme': {
      id: '/varme'
      path: '/varme'
      fullPath: '/varme'
      preLoaderRoute: typeof VarmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varkart': {
      id: '/varkart'
      path: '/varkart'
      fullPath: '/varkart'
      preLoaderRoute: typeof VarkartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varfavoritter': {
      id: '/varfavoritter'
      path: '/varfavoritter'
      fullPath: '/varfavoritter'
      preLoaderRoute: typeof VarfavoritterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/var': {
      id: '/var'
      path: '/var'
      fullPath: '/var'
      preLoaderRoute: typeof VarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vakttarnet': {
      id: '/vakttarnet'
      path: '/vakttarnet'
      fullPath: '/vakttarnet'
      preLoaderRoute: typeof VakttarnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utlan': {
      id: '/utlan'
      path: '/utlan'
      fullPath: '/utlan'
      preLoaderRoute: typeof UtlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trening': {
      id: '/trening'
      path: '/trening'
      fullPath: '/trening'
      preLoaderRoute: typeof TreningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stromkroniken': {
      id: '/stromkroniken'
      path: '/stromkroniken'
      fullPath: '/stromkroniken'
      preLoaderRoute: typeof StromkronikenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stovsugeren': {
      id: '/stovsugeren'
      path: '/stovsugeren'
      fullPath: '/stovsugeren'
      preLoaderRoute: typeof StovsugerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steintavle-2': {
      id: '/steintavle-2'
      path: '/steintavle-2'
      fullPath: '/steintavle-2'
      preLoaderRoute: typeof Steintavle2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steintavle': {
      id: '/steintavle'
      path: '/steintavle'
      fullPath: '/steintavle'
      preLoaderRoute: typeof SteintavleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smarthus': {
      id: '/smarthus'
      path: '/smarthus'
      fullPath: '/smarthus'
      preLoaderRoute: typeof SmarthusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-dashbord': {
      id: '/smart-dashbord'
      path: '/smart-dashbord'
      fullPath: '/smart-dashbord'
      preLoaderRoute: typeof SmartDashbordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skatte-utregningen': {
      id: '/skatte-utregningen'
      path: '/skatte-utregningen'
      fullPath: '/skatte-utregningen'
      preLoaderRoute: typeof SkatteUtregningenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roborock': {
      id: '/roborock'
      path: '/roborock'
      fullPath: '/roborock'
      preLoaderRoute: typeof RoborockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regnskap': {
      id: '/regnskap'
      path: '/regnskap'
      fullPath: '/regnskap'
      preLoaderRoute: typeof RegnskapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/push-varslinger': {
      id: '/push-varslinger'
      path: '/push-varslinger'
      fullPath: '/push-varslinger'
      preLoaderRoute: typeof PushVarslingerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pollen': {
      id: '/pollen'
      path: '/pollen'
      fullPath: '/pollen'
      preLoaderRoute: typeof PollenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lys': {
      id: '/lys'
      path: '/lys'
      fullPath: '/lys'
      preLoaderRoute: typeof LysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linketur': {
      id: '/linketur'
      path: '/linketur'
      fullPath: '/linketur'
      preLoaderRoute: typeof LinketurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvitteringer': {
      id: '/kvitteringer'
      path: '/kvitteringer'
      fullPath: '/kvitteringer'
      preLoaderRoute: typeof KvitteringerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosthold': {
      id: '/kosthold'
      path: '/kosthold'
      fullPath: '/kosthold'
      preLoaderRoute: typeof KostholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jaguar': {
      id: '/jaguar'
      path: '/jaguar'
      fullPath: '/jaguar'
      preLoaderRoute: typeof JaguarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iphone-app': {
      id: '/iphone-app'
      path: '/iphone-app'
      fullPath: '/iphone-app'
      preLoaderRoute: typeof IphoneAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hytta': {
      id: '/hytta'
      path: '/hytta'
      fullPath: '/hytta'
      preLoaderRoute: typeof HyttaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gressklipper': {
      id: '/gressklipper'
      path: '/gressklipper'
      fullPath: '/gressklipper'
      preLoaderRoute: typeof GressklipperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budsjett': {
      id: '/budsjett'
      path: '/budsjett'
      fullPath: '/budsjett'
      preLoaderRoute: typeof BudsjettRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruksanvisning': {
      id: '/bruksanvisning'
      path: '/bruksanvisning'
      fullPath: '/bruksanvisning'
      preLoaderRoute: typeof BruksanvisningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/log-pulse': {
      id: '/hooks/log-pulse'
      path: '/hooks/log-pulse'
      fullPath: '/hooks/log-pulse'
      preLoaderRoute: typeof HooksLogPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/start': {
      id: '/api/strava/start'
      path: '/api/strava/start'
      fullPath: '/api/strava/start'
      preLoaderRoute: typeof ApiStravaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/callback': {
      id: '/api/strava/callback'
      path: '/api/strava/callback'
      fullPath: '/api/strava/callback'
      preLoaderRoute: typeof ApiStravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homey/start': {
      id: '/api/homey/start'
      path: '/api/homey/start'
      fullPath: '/api/homey/start'
      preLoaderRoute: typeof ApiHomeyStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homey/callback': {
      id: '/api/homey/callback'
      path: '/api/homey/callback'
      fullPath: '/api/homey/callback'
      preLoaderRoute: typeof ApiHomeyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/voc-poll': {
      id: '/api/public/hooks/voc-poll'
      path: '/api/public/hooks/voc-poll'
      fullPath: '/api/public/hooks/voc-poll'
      preLoaderRoute: typeof ApiPublicHooksVocPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/strava-poll': {
      id: '/api/public/hooks/strava-poll'
      path: '/api/public/hooks/strava-poll'
      fullPath: '/api/public/hooks/strava-poll'
      preLoaderRoute: typeof ApiPublicHooksStravaPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/snapshot-tibber-daily': {
      id: '/api/public/hooks/snapshot-tibber-daily'
      path: '/api/public/hooks/snapshot-tibber-daily'
      fullPath: '/api/public/hooks/snapshot-tibber-daily'
      preLoaderRoute: typeof ApiPublicHooksSnapshotTibberDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/snapshot-pulse': {
      id: '/api/public/hooks/snapshot-pulse'
      path: '/api/public/hooks/snapshot-pulse'
      fullPath: '/api/public/hooks/snapshot-pulse'
      preLoaderRoute: typeof ApiPublicHooksSnapshotPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/radon-poll': {
      id: '/api/public/hooks/radon-poll'
      path: '/api/public/hooks/radon-poll'
      fullPath: '/api/public/hooks/radon-poll'
      preLoaderRoute: typeof ApiPublicHooksRadonPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/open-meteo-warm': {
      id: '/api/public/hooks/open-meteo-warm'
      path: '/api/public/hooks/open-meteo-warm'
      fullPath: '/api/public/hooks/open-meteo-warm'
      preLoaderRoute: typeof ApiPublicHooksOpenMeteoWarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/netatmo-climate-refresh': {
      id: '/api/public/hooks/netatmo-climate-refresh'
      path: '/api/public/hooks/netatmo-climate-refresh'
      fullPath: '/api/public/hooks/netatmo-climate-refresh'
      preLoaderRoute: typeof ApiPublicHooksNetatmoClimateRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/homey-sensor-poll': {
      id: '/api/public/hooks/homey-sensor-poll'
      path: '/api/public/hooks/homey-sensor-poll'
      fullPath: '/api/public/hooks/homey-sensor-poll'
      preLoaderRoute: typeof ApiPublicHooksHomeySensorPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/gardena-poll': {
      id: '/api/public/hooks/gardena-poll'
      path: '/api/public/hooks/gardena-poll'
      fullPath: '/api/public/hooks/gardena-poll'
      preLoaderRoute: typeof ApiPublicHooksGardenaPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/eufy-poll': {
      id: '/api/public/hooks/eufy-poll'
      path: '/api/public/hooks/eufy-poll'
      fullPath: '/api/public/hooks/eufy-poll'
      preLoaderRoute: typeof ApiPublicHooksEufyPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/eufy': {
      id: '/api/public/hooks/eufy'
      path: '/api/public/hooks/eufy'
      fullPath: '/api/public/hooks/eufy'
      preLoaderRoute: typeof ApiPublicHooksEufyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-pbth-history': {
      id: '/api/public/hooks/backfill-pbth-history'
      path: '/api/public/hooks/backfill-pbth-history'
      fullPath: '/api/public/hooks/backfill-pbth-history'
      preLoaderRoute: typeof ApiPublicHooksBackfillPbthHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/air-quality-history-daily': {
      id: '/api/public/hooks/air-quality-history-daily'
      path: '/api/public/hooks/air-quality-history-daily'
      fullPath: '/api/public/hooks/air-quality-history-daily'
      preLoaderRoute: typeof ApiPublicHooksAirQualityHistoryDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agenda-push': {
      id: '/api/public/hooks/agenda-push'
      path: '/api/public/hooks/agenda-push'
      fullPath: '/api/public/hooks/agenda-push'
      preLoaderRoute: typeof ApiPublicHooksAgendaPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  BruksanvisningRoute: BruksanvisningRoute,
  BudsjettRoute: BudsjettRoute,
  GressklipperRoute: GressklipperRoute,
  HyttaRoute: HyttaRoute,
  IphoneAppRoute: IphoneAppRoute,
  JaguarRoute: JaguarRoute,
  KostholdRoute: KostholdRoute,
  KvitteringerRoute: KvitteringerRoute,
  LinketurRoute: LinketurRoute,
  LysRoute: LysRoute,
  PollenRoute: PollenRoute,
  PushVarslingerRoute: PushVarslingerRoute,
  RegnskapRoute: RegnskapRoute,
  RoborockRoute: RoborockRoute,
  SkatteUtregningenRoute: SkatteUtregningenRoute,
  SmartDashbordRoute: SmartDashbordRoute,
  SmarthusRoute: SmarthusRoute,
  SteintavleRoute: SteintavleRoute,
  Steintavle2Route: Steintavle2Route,
  StovsugerenRoute: StovsugerenRoute,
  StromkronikenRoute: StromkronikenRoute,
  TreningRoute: TreningRoute,
  UtlanRoute: UtlanRoute,
  VakttarnetRoute: VakttarnetRoute,
  VarRoute: VarRoute,
  VarfavoritterRoute: VarfavoritterRoute,
  VarkartRoute: VarkartRoute,
  VarmeRoute: VarmeRoute,
  YtelseRoute: YtelseRoute,
  HooksLogPulseRoute: HooksLogPulseRoute,
  ApiHomeyCallbackRoute: ApiHomeyCallbackRoute,
  ApiHomeyStartRoute: ApiHomeyStartRoute,
  ApiStravaCallbackRoute: ApiStravaCallbackRoute,
  ApiStravaStartRoute: ApiStravaStartRoute,
  ApiPublicHooksAgendaPushRoute: ApiPublicHooksAgendaPushRoute,
  ApiPublicHooksAirQualityHistoryDailyRoute:
    ApiPublicHooksAirQualityHistoryDailyRoute,
  ApiPublicHooksBackfillPbthHistoryRoute:
    ApiPublicHooksBackfillPbthHistoryRoute,
  ApiPublicHooksEufyRoute: ApiPublicHooksEufyRoute,
  ApiPublicHooksEufyPollRoute: ApiPublicHooksEufyPollRoute,
  ApiPublicHooksGardenaPollRoute: ApiPublicHooksGardenaPollRoute,
  ApiPublicHooksHomeySensorPollRoute: ApiPublicHooksHomeySensorPollRoute,
  ApiPublicHooksNetatmoClimateRefreshRoute:
    ApiPublicHooksNetatmoClimateRefreshRoute,
  ApiPublicHooksOpenMeteoWarmRoute: ApiPublicHooksOpenMeteoWarmRoute,
  ApiPublicHooksRadonPollRoute: ApiPublicHooksRadonPollRoute,
  ApiPublicHooksSnapshotPulseRoute: ApiPublicHooksSnapshotPulseRoute,
  ApiPublicHooksSnapshotTibberDailyRoute:
    ApiPublicHooksSnapshotTibberDailyRoute,
  ApiPublicHooksStravaPollRoute: ApiPublicHooksStravaPollRoute,
  ApiPublicHooksVocPollRoute: ApiPublicHooksVocPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
