/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VarslerRouteImport } from './routes/varsler'
import { Route as VarRouteImport } from './routes/var'
import { Route as VakttarnetRouteImport } from './routes/vakttarnet'
import { Route as TurerRouteImport } from './routes/turer'
import { Route as TreningRouteImport } from './routes/trening'
import { Route as StromkronikenRouteImport } from './routes/stromkroniken'
import { Route as SteintavleRouteImport } from './routes/steintavle'
import { Route as SmarthusRouteImport } from './routes/smarthus'
import { Route as RoborockRouteImport } from './routes/roborock'
import { Route as PushVarslingerRouteImport } from './routes/push-varslinger'
import { Route as PollenRouteImport } from './routes/pollen'
import { Route as OppussingHyttaRouteImport } from './routes/oppussing-hytta'
import { Route as OppussingBorgenRouteImport } from './routes/oppussing-borgen'
import { Route as MatvarerRouteImport } from './routes/matvarer'
import { Route as LysRouteImport } from './routes/lys'
import { Route as KvitteringerRouteImport } from './routes/kvitteringer'
import { Route as HyttaRouteImport } from './routes/hytta'
import { Route as HundeneRouteImport } from './routes/hundene'
import { Route as GotSagaRouteImport } from './routes/got-saga'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksLogPulseRouteImport } from './routes/hooks.log-pulse'
import { Route as ApiStravaStartRouteImport } from './routes/api.strava.start'
import { Route as ApiStravaCallbackRouteImport } from './routes/api.strava.callback'
import { Route as ApiHomeyStartRouteImport } from './routes/api.homey.start'
import { Route as ApiHomeyCallbackRouteImport } from './routes/api.homey.callback'
import { Route as ApiPublicHooksSnapshotTibberDailyRouteImport } from './routes/api.public.hooks.snapshot-tibber-daily'
import { Route as ApiPublicHooksSnapshotPulseRouteImport } from './routes/api.public.hooks.snapshot-pulse'
import { Route as ApiPublicHooksEufyPollRouteImport } from './routes/api/public/hooks/eufy-poll'
import { Route as ApiPublicHooksEufyRouteImport } from './routes/api/public/hooks/eufy'
import { Route as ApiPublicHooksBackfillPbthHistoryRouteImport } from './routes/api.public.hooks.backfill-pbth-history'
import { Route as ApiPublicHooksAgendaPushRouteImport } from './routes/api.public.hooks.agenda-push'

const VarslerRoute = VarslerRouteImport.update({
  id: '/varsler',
  path: '/varsler',
  getParentRoute: () => rootRouteImport,
} as any)
const VarRoute = VarRouteImport.update({
  id: '/var',
  path: '/var',
  getParentRoute: () => rootRouteImport,
} as any)
const VakttarnetRoute = VakttarnetRouteImport.update({
  id: '/vakttarnet',
  path: '/vakttarnet',
  getParentRoute: () => rootRouteImport,
} as any)
const TurerRoute = TurerRouteImport.update({
  id: '/turer',
  path: '/turer',
  getParentRoute: () => rootRouteImport,
} as any)
const TreningRoute = TreningRouteImport.update({
  id: '/trening',
  path: '/trening',
  getParentRoute: () => rootRouteImport,
} as any)
const StromkronikenRoute = StromkronikenRouteImport.update({
  id: '/stromkroniken',
  path: '/stromkroniken',
  getParentRoute: () => rootRouteImport,
} as any)
const SteintavleRoute = SteintavleRouteImport.update({
  id: '/steintavle',
  path: '/steintavle',
  getParentRoute: () => rootRouteImport,
} as any)
const SmarthusRoute = SmarthusRouteImport.update({
  id: '/smarthus',
  path: '/smarthus',
  getParentRoute: () => rootRouteImport,
} as any)
const RoborockRoute = RoborockRouteImport.update({
  id: '/roborock',
  path: '/roborock',
  getParentRoute: () => rootRouteImport,
} as any)
const PushVarslingerRoute = PushVarslingerRouteImport.update({
  id: '/push-varslinger',
  path: '/push-varslinger',
  getParentRoute: () => rootRouteImport,
} as any)
const PollenRoute = PollenRouteImport.update({
  id: '/pollen',
  path: '/pollen',
  getParentRoute: () => rootRouteImport,
} as any)
const OppussingHyttaRoute = OppussingHyttaRouteImport.update({
  id: '/oppussing-hytta',
  path: '/oppussing-hytta',
  getParentRoute: () => rootRouteImport,
} as any)
const OppussingBorgenRoute = OppussingBorgenRouteImport.update({
  id: '/oppussing-borgen',
  path: '/oppussing-borgen',
  getParentRoute: () => rootRouteImport,
} as any)
const MatvarerRoute = MatvarerRouteImport.update({
  id: '/matvarer',
  path: '/matvarer',
  getParentRoute: () => rootRouteImport,
} as any)
const LysRoute = LysRouteImport.update({
  id: '/lys',
  path: '/lys',
  getParentRoute: () => rootRouteImport,
} as any)
const KvitteringerRoute = KvitteringerRouteImport.update({
  id: '/kvitteringer',
  path: '/kvitteringer',
  getParentRoute: () => rootRouteImport,
} as any)
const HyttaRoute = HyttaRouteImport.update({
  id: '/hytta',
  path: '/hytta',
  getParentRoute: () => rootRouteImport,
} as any)
const HundeneRoute = HundeneRouteImport.update({
  id: '/hundene',
  path: '/hundene',
  getParentRoute: () => rootRouteImport,
} as any)
const GotSagaRoute = GotSagaRouteImport.update({
  id: '/got-saga',
  path: '/got-saga',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksLogPulseRoute = HooksLogPulseRouteImport.update({
  id: '/hooks/log-pulse',
  path: '/hooks/log-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaStartRoute = ApiStravaStartRouteImport.update({
  id: '/api/strava/start',
  path: '/api/strava/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaCallbackRoute = ApiStravaCallbackRouteImport.update({
  id: '/api/strava/callback',
  path: '/api/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeyStartRoute = ApiHomeyStartRouteImport.update({
  id: '/api/homey/start',
  path: '/api/homey/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeyCallbackRoute = ApiHomeyCallbackRouteImport.update({
  id: '/api/homey/callback',
  path: '/api/homey/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSnapshotTibberDailyRoute =
  ApiPublicHooksSnapshotTibberDailyRouteImport.update({
    id: '/api/public/hooks/snapshot-tibber-daily',
    path: '/api/public/hooks/snapshot-tibber-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSnapshotPulseRoute =
  ApiPublicHooksSnapshotPulseRouteImport.update({
    id: '/api/public/hooks/snapshot-pulse',
    path: '/api/public/hooks/snapshot-pulse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEufyPollRoute = ApiPublicHooksEufyPollRouteImport.update({
  id: '/api/public/hooks/eufy-poll',
  path: '/api/public/hooks/eufy-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEufyRoute = ApiPublicHooksEufyRouteImport.update({
  id: '/api/public/hooks/eufy',
  path: '/api/public/hooks/eufy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBackfillPbthHistoryRoute =
  ApiPublicHooksBackfillPbthHistoryRouteImport.update({
    id: '/api/public/hooks/backfill-pbth-history',
    path: '/api/public/hooks/backfill-pbth-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgendaPushRoute =
  ApiPublicHooksAgendaPushRouteImport.update({
    id: '/api/public/hooks/agenda-push',
    path: '/api/public/hooks/agenda-push',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/got-saga': typeof GotSagaRoute
  '/hundene': typeof HundeneRoute
  '/hytta': typeof HyttaRoute
  '/kvitteringer': typeof KvitteringerRoute
  '/lys': typeof LysRoute
  '/matvarer': typeof MatvarerRoute
  '/oppussing-borgen': typeof OppussingBorgenRoute
  '/oppussing-hytta': typeof OppussingHyttaRoute
  '/pollen': typeof PollenRoute
  '/push-varslinger': typeof PushVarslingerRoute
  '/roborock': typeof RoborockRoute
  '/smarthus': typeof SmarthusRoute
  '/steintavle': typeof SteintavleRoute
  '/stromkroniken': typeof StromkronikenRoute
  '/trening': typeof TreningRoute
  '/turer': typeof TurerRoute
  '/vakttarnet': typeof VakttarnetRoute
  '/var': typeof VarRoute
  '/varsler': typeof VarslerRoute
  '/hooks/log-pulse': typeof HooksLogPulseRoute
  '/api/homey/callback': typeof ApiHomeyCallbackRoute
  '/api/homey/start': typeof ApiHomeyStartRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/strava/start': typeof ApiStravaStartRoute
  '/api/public/hooks/agenda-push': typeof ApiPublicHooksAgendaPushRoute
  '/api/public/hooks/backfill-pbth-history': typeof ApiPublicHooksBackfillPbthHistoryRoute
  '/api/public/hooks/eufy': typeof ApiPublicHooksEufyRoute
  '/api/public/hooks/eufy-poll': typeof ApiPublicHooksEufyPollRoute
  '/api/public/hooks/snapshot-pulse': typeof ApiPublicHooksSnapshotPulseRoute
  '/api/public/hooks/snapshot-tibber-daily': typeof ApiPublicHooksSnapshotTibberDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/got-saga': typeof GotSagaRoute
  '/hundene': typeof HundeneRoute
  '/hytta': typeof HyttaRoute
  '/kvitteringer': typeof KvitteringerRoute
  '/lys': typeof LysRoute
  '/matvarer': typeof MatvarerRoute
  '/oppussing-borgen': typeof OppussingBorgenRoute
  '/oppussing-hytta': typeof OppussingHyttaRoute
  '/pollen': typeof PollenRoute
  '/push-varslinger': typeof PushVarslingerRoute
  '/roborock': typeof RoborockRoute
  '/smarthus': typeof SmarthusRoute
  '/steintavle': typeof SteintavleRoute
  '/stromkroniken': typeof StromkronikenRoute
  '/trening': typeof TreningRoute
  '/turer': typeof TurerRoute
  '/vakttarnet': typeof VakttarnetRoute
  '/var': typeof VarRoute
  '/varsler': typeof VarslerRoute
  '/hooks/log-pulse': typeof HooksLogPulseRoute
  '/api/homey/callback': typeof ApiHomeyCallbackRoute
  '/api/homey/start': typeof ApiHomeyStartRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/strava/start': typeof ApiStravaStartRoute
  '/api/public/hooks/agenda-push': typeof ApiPublicHooksAgendaPushRoute
  '/api/public/hooks/backfill-pbth-history': typeof ApiPublicHooksBackfillPbthHistoryRoute
  '/api/public/hooks/eufy': typeof ApiPublicHooksEufyRoute
  '/api/public/hooks/eufy-poll': typeof ApiPublicHooksEufyPollRoute
  '/api/public/hooks/snapshot-pulse': typeof ApiPublicHooksSnapshotPulseRoute
  '/api/public/hooks/snapshot-tibber-daily': typeof ApiPublicHooksSnapshotTibberDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/got-saga': typeof GotSagaRoute
  '/hundene': typeof HundeneRoute
  '/hytta': typeof HyttaRoute
  '/kvitteringer': typeof KvitteringerRoute
  '/lys': typeof LysRoute
  '/matvarer': typeof MatvarerRoute
  '/oppussing-borgen': typeof OppussingBorgenRoute
  '/oppussing-hytta': typeof OppussingHyttaRoute
  '/pollen': typeof PollenRoute
  '/push-varslinger': typeof PushVarslingerRoute
  '/roborock': typeof RoborockRoute
  '/smarthus': typeof SmarthusRoute
  '/steintavle': typeof SteintavleRoute
  '/stromkroniken': typeof StromkronikenRoute
  '/trening': typeof TreningRoute
  '/turer': typeof TurerRoute
  '/vakttarnet': typeof VakttarnetRoute
  '/var': typeof VarRoute
  '/varsler': typeof VarslerRoute
  '/hooks/log-pulse': typeof HooksLogPulseRoute
  '/api/homey/callback': typeof ApiHomeyCallbackRoute
  '/api/homey/start': typeof ApiHomeyStartRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/strava/start': typeof ApiStravaStartRoute
  '/api/public/hooks/agenda-push': typeof ApiPublicHooksAgendaPushRoute
  '/api/public/hooks/backfill-pbth-history': typeof ApiPublicHooksBackfillPbthHistoryRoute
  '/api/public/hooks/eufy': typeof ApiPublicHooksEufyRoute
  '/api/public/hooks/eufy-poll': typeof ApiPublicHooksEufyPollRoute
  '/api/public/hooks/snapshot-pulse': typeof ApiPublicHooksSnapshotPulseRoute
  '/api/public/hooks/snapshot-tibber-daily': typeof ApiPublicHooksSnapshotTibberDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/got-saga'
    | '/hundene'
    | '/hytta'
    | '/kvitteringer'
    | '/lys'
    | '/matvarer'
    | '/oppussing-borgen'
    | '/oppussing-hytta'
    | '/pollen'
    | '/push-varslinger'
    | '/roborock'
    | '/smarthus'
    | '/steintavle'
    | '/stromkroniken'
    | '/trening'
    | '/turer'
    | '/vakttarnet'
    | '/var'
    | '/varsler'
    | '/hooks/log-pulse'
    | '/api/homey/callback'
    | '/api/homey/start'
    | '/api/strava/callback'
    | '/api/strava/start'
    | '/api/public/hooks/agenda-push'
    | '/api/public/hooks/backfill-pbth-history'
    | '/api/public/hooks/eufy'
    | '/api/public/hooks/eufy-poll'
    | '/api/public/hooks/snapshot-pulse'
    | '/api/public/hooks/snapshot-tibber-daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/got-saga'
    | '/hundene'
    | '/hytta'
    | '/kvitteringer'
    | '/lys'
    | '/matvarer'
    | '/oppussing-borgen'
    | '/oppussing-hytta'
    | '/pollen'
    | '/push-varslinger'
    | '/roborock'
    | '/smarthus'
    | '/steintavle'
    | '/stromkroniken'
    | '/trening'
    | '/turer'
    | '/vakttarnet'
    | '/var'
    | '/varsler'
    | '/hooks/log-pulse'
    | '/api/homey/callback'
    | '/api/homey/start'
    | '/api/strava/callback'
    | '/api/strava/start'
    | '/api/public/hooks/agenda-push'
    | '/api/public/hooks/backfill-pbth-history'
    | '/api/public/hooks/eufy'
    | '/api/public/hooks/eufy-poll'
    | '/api/public/hooks/snapshot-pulse'
    | '/api/public/hooks/snapshot-tibber-daily'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/got-saga'
    | '/hundene'
    | '/hytta'
    | '/kvitteringer'
    | '/lys'
    | '/matvarer'
    | '/oppussing-borgen'
    | '/oppussing-hytta'
    | '/pollen'
    | '/push-varslinger'
    | '/roborock'
    | '/smarthus'
    | '/steintavle'
    | '/stromkroniken'
    | '/trening'
    | '/turer'
    | '/vakttarnet'
    | '/var'
    | '/varsler'
    | '/hooks/log-pulse'
    | '/api/homey/callback'
    | '/api/homey/start'
    | '/api/strava/callback'
    | '/api/strava/start'
    | '/api/public/hooks/agenda-push'
    | '/api/public/hooks/backfill-pbth-history'
    | '/api/public/hooks/eufy'
    | '/api/public/hooks/eufy-poll'
    | '/api/public/hooks/snapshot-pulse'
    | '/api/public/hooks/snapshot-tibber-daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  GotSagaRoute: typeof GotSagaRoute
  HundeneRoute: typeof HundeneRoute
  HyttaRoute: typeof HyttaRoute
  KvitteringerRoute: typeof KvitteringerRoute
  LysRoute: typeof LysRoute
  MatvarerRoute: typeof MatvarerRoute
  OppussingBorgenRoute: typeof OppussingBorgenRoute
  OppussingHyttaRoute: typeof OppussingHyttaRoute
  PollenRoute: typeof PollenRoute
  PushVarslingerRoute: typeof PushVarslingerRoute
  RoborockRoute: typeof RoborockRoute
  SmarthusRoute: typeof SmarthusRoute
  SteintavleRoute: typeof SteintavleRoute
  StromkronikenRoute: typeof StromkronikenRoute
  TreningRoute: typeof TreningRoute
  TurerRoute: typeof TurerRoute
  VakttarnetRoute: typeof VakttarnetRoute
  VarRoute: typeof VarRoute
  VarslerRoute: typeof VarslerRoute
  HooksLogPulseRoute: typeof HooksLogPulseRoute
  ApiHomeyCallbackRoute: typeof ApiHomeyCallbackRoute
  ApiHomeyStartRoute: typeof ApiHomeyStartRoute
  ApiStravaCallbackRoute: typeof ApiStravaCallbackRoute
  ApiStravaStartRoute: typeof ApiStravaStartRoute
  ApiPublicHooksAgendaPushRoute: typeof ApiPublicHooksAgendaPushRoute
  ApiPublicHooksBackfillPbthHistoryRoute: typeof ApiPublicHooksBackfillPbthHistoryRoute
  ApiPublicHooksEufyRoute: typeof ApiPublicHooksEufyRoute
  ApiPublicHooksEufyPollRoute: typeof ApiPublicHooksEufyPollRoute
  ApiPublicHooksSnapshotPulseRoute: typeof ApiPublicHooksSnapshotPulseRoute
  ApiPublicHooksSnapshotTibberDailyRoute: typeof ApiPublicHooksSnapshotTibberDailyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/varsler': {
      id: '/varsler'
      path: '/varsler'
      fullPath: '/varsler'
      preLoaderRoute: typeof VarslerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/var': {
      id: '/var'
      path: '/var'
      fullPath: '/var'
      preLoaderRoute: typeof VarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vakttarnet': {
      id: '/vakttarnet'
      path: '/vakttarnet'
      fullPath: '/vakttarnet'
      preLoaderRoute: typeof VakttarnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turer': {
      id: '/turer'
      path: '/turer'
      fullPath: '/turer'
      preLoaderRoute: typeof TurerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trening': {
      id: '/trening'
      path: '/trening'
      fullPath: '/trening'
      preLoaderRoute: typeof TreningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stromkroniken': {
      id: '/stromkroniken'
      path: '/stromkroniken'
      fullPath: '/stromkroniken'
      preLoaderRoute: typeof StromkronikenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steintavle': {
      id: '/steintavle'
      path: '/steintavle'
      fullPath: '/steintavle'
      preLoaderRoute: typeof SteintavleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smarthus': {
      id: '/smarthus'
      path: '/smarthus'
      fullPath: '/smarthus'
      preLoaderRoute: typeof SmarthusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roborock': {
      id: '/roborock'
      path: '/roborock'
      fullPath: '/roborock'
      preLoaderRoute: typeof RoborockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/push-varslinger': {
      id: '/push-varslinger'
      path: '/push-varslinger'
      fullPath: '/push-varslinger'
      preLoaderRoute: typeof PushVarslingerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pollen': {
      id: '/pollen'
      path: '/pollen'
      fullPath: '/pollen'
      preLoaderRoute: typeof PollenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oppussing-hytta': {
      id: '/oppussing-hytta'
      path: '/oppussing-hytta'
      fullPath: '/oppussing-hytta'
      preLoaderRoute: typeof OppussingHyttaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oppussing-borgen': {
      id: '/oppussing-borgen'
      path: '/oppussing-borgen'
      fullPath: '/oppussing-borgen'
      preLoaderRoute: typeof OppussingBorgenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matvarer': {
      id: '/matvarer'
      path: '/matvarer'
      fullPath: '/matvarer'
      preLoaderRoute: typeof MatvarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lys': {
      id: '/lys'
      path: '/lys'
      fullPath: '/lys'
      preLoaderRoute: typeof LysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvitteringer': {
      id: '/kvitteringer'
      path: '/kvitteringer'
      fullPath: '/kvitteringer'
      preLoaderRoute: typeof KvitteringerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hytta': {
      id: '/hytta'
      path: '/hytta'
      fullPath: '/hytta'
      preLoaderRoute: typeof HyttaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hundene': {
      id: '/hundene'
      path: '/hundene'
      fullPath: '/hundene'
      preLoaderRoute: typeof HundeneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/got-saga': {
      id: '/got-saga'
      path: '/got-saga'
      fullPath: '/got-saga'
      preLoaderRoute: typeof GotSagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/log-pulse': {
      id: '/hooks/log-pulse'
      path: '/hooks/log-pulse'
      fullPath: '/hooks/log-pulse'
      preLoaderRoute: typeof HooksLogPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/start': {
      id: '/api/strava/start'
      path: '/api/strava/start'
      fullPath: '/api/strava/start'
      preLoaderRoute: typeof ApiStravaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/callback': {
      id: '/api/strava/callback'
      path: '/api/strava/callback'
      fullPath: '/api/strava/callback'
      preLoaderRoute: typeof ApiStravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homey/start': {
      id: '/api/homey/start'
      path: '/api/homey/start'
      fullPath: '/api/homey/start'
      preLoaderRoute: typeof ApiHomeyStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homey/callback': {
      id: '/api/homey/callback'
      path: '/api/homey/callback'
      fullPath: '/api/homey/callback'
      preLoaderRoute: typeof ApiHomeyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/snapshot-tibber-daily': {
      id: '/api/public/hooks/snapshot-tibber-daily'
      path: '/api/public/hooks/snapshot-tibber-daily'
      fullPath: '/api/public/hooks/snapshot-tibber-daily'
      preLoaderRoute: typeof ApiPublicHooksSnapshotTibberDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/snapshot-pulse': {
      id: '/api/public/hooks/snapshot-pulse'
      path: '/api/public/hooks/snapshot-pulse'
      fullPath: '/api/public/hooks/snapshot-pulse'
      preLoaderRoute: typeof ApiPublicHooksSnapshotPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/eufy-poll': {
      id: '/api/public/hooks/eufy-poll'
      path: '/api/public/hooks/eufy-poll'
      fullPath: '/api/public/hooks/eufy-poll'
      preLoaderRoute: typeof ApiPublicHooksEufyPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/eufy': {
      id: '/api/public/hooks/eufy'
      path: '/api/public/hooks/eufy'
      fullPath: '/api/public/hooks/eufy'
      preLoaderRoute: typeof ApiPublicHooksEufyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-pbth-history': {
      id: '/api/public/hooks/backfill-pbth-history'
      path: '/api/public/hooks/backfill-pbth-history'
      fullPath: '/api/public/hooks/backfill-pbth-history'
      preLoaderRoute: typeof ApiPublicHooksBackfillPbthHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agenda-push': {
      id: '/api/public/hooks/agenda-push'
      path: '/api/public/hooks/agenda-push'
      fullPath: '/api/public/hooks/agenda-push'
      preLoaderRoute: typeof ApiPublicHooksAgendaPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  GotSagaRoute: GotSagaRoute,
  HundeneRoute: HundeneRoute,
  HyttaRoute: HyttaRoute,
  KvitteringerRoute: KvitteringerRoute,
  LysRoute: LysRoute,
  MatvarerRoute: MatvarerRoute,
  OppussingBorgenRoute: OppussingBorgenRoute,
  OppussingHyttaRoute: OppussingHyttaRoute,
  PollenRoute: PollenRoute,
  PushVarslingerRoute: PushVarslingerRoute,
  RoborockRoute: RoborockRoute,
  SmarthusRoute: SmarthusRoute,
  SteintavleRoute: SteintavleRoute,
  StromkronikenRoute: StromkronikenRoute,
  TreningRoute: TreningRoute,
  TurerRoute: TurerRoute,
  VakttarnetRoute: VakttarnetRoute,
  VarRoute: VarRoute,
  VarslerRoute: VarslerRoute,
  HooksLogPulseRoute: HooksLogPulseRoute,
  ApiHomeyCallbackRoute: ApiHomeyCallbackRoute,
  ApiHomeyStartRoute: ApiHomeyStartRoute,
  ApiStravaCallbackRoute: ApiStravaCallbackRoute,
  ApiStravaStartRoute: ApiStravaStartRoute,
  ApiPublicHooksAgendaPushRoute: ApiPublicHooksAgendaPushRoute,
  ApiPublicHooksBackfillPbthHistoryRoute:
    ApiPublicHooksBackfillPbthHistoryRoute,
  ApiPublicHooksEufyRoute: ApiPublicHooksEufyRoute,
  ApiPublicHooksEufyPollRoute: ApiPublicHooksEufyPollRoute,
  ApiPublicHooksSnapshotPulseRoute: ApiPublicHooksSnapshotPulseRoute,
  ApiPublicHooksSnapshotTibberDailyRoute:
    ApiPublicHooksSnapshotTibberDailyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
