/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VarRouteImport } from './routes/var'
import { Route as TreningRouteImport } from './routes/trening'
import { Route as SmarthusRouteImport } from './routes/smarthus'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HyttaRouteImport } from './routes/hytta'
import { Route as HundeneRouteImport } from './routes/hundene'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHomeyStartRouteImport } from './routes/api.homey.start'
import { Route as ApiHomeyCallbackRouteImport } from './routes/api.homey.callback'

const VarRoute = VarRouteImport.update({
  id: '/var',
  path: '/var',
  getParentRoute: () => rootRouteImport,
} as any)
const TreningRoute = TreningRouteImport.update({
  id: '/trening',
  path: '/trening',
  getParentRoute: () => rootRouteImport,
} as any)
const SmarthusRoute = SmarthusRouteImport.update({
  id: '/smarthus',
  path: '/smarthus',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HyttaRoute = HyttaRouteImport.update({
  id: '/hytta',
  path: '/hytta',
  getParentRoute: () => rootRouteImport,
} as any)
const HundeneRoute = HundeneRouteImport.update({
  id: '/hundene',
  path: '/hundene',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeyStartRoute = ApiHomeyStartRouteImport.update({
  id: '/api/homey/start',
  path: '/api/homey/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeyCallbackRoute = ApiHomeyCallbackRouteImport.update({
  id: '/api/homey/callback',
  path: '/api/homey/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/hundene': typeof HundeneRoute
  '/hytta': typeof HyttaRoute
  '/login': typeof LoginRoute
  '/smarthus': typeof SmarthusRoute
  '/trening': typeof TreningRoute
  '/var': typeof VarRoute
  '/api/homey/callback': typeof ApiHomeyCallbackRoute
  '/api/homey/start': typeof ApiHomeyStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/hundene': typeof HundeneRoute
  '/hytta': typeof HyttaRoute
  '/login': typeof LoginRoute
  '/smarthus': typeof SmarthusRoute
  '/trening': typeof TreningRoute
  '/var': typeof VarRoute
  '/api/homey/callback': typeof ApiHomeyCallbackRoute
  '/api/homey/start': typeof ApiHomeyStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/hundene': typeof HundeneRoute
  '/hytta': typeof HyttaRoute
  '/login': typeof LoginRoute
  '/smarthus': typeof SmarthusRoute
  '/trening': typeof TreningRoute
  '/var': typeof VarRoute
  '/api/homey/callback': typeof ApiHomeyCallbackRoute
  '/api/homey/start': typeof ApiHomeyStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/hundene'
    | '/hytta'
    | '/login'
    | '/smarthus'
    | '/trening'
    | '/var'
    | '/api/homey/callback'
    | '/api/homey/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/hundene'
    | '/hytta'
    | '/login'
    | '/smarthus'
    | '/trening'
    | '/var'
    | '/api/homey/callback'
    | '/api/homey/start'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/hundene'
    | '/hytta'
    | '/login'
    | '/smarthus'
    | '/trening'
    | '/var'
    | '/api/homey/callback'
    | '/api/homey/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  HundeneRoute: typeof HundeneRoute
  HyttaRoute: typeof HyttaRoute
  LoginRoute: typeof LoginRoute
  SmarthusRoute: typeof SmarthusRoute
  TreningRoute: typeof TreningRoute
  VarRoute: typeof VarRoute
  ApiHomeyCallbackRoute: typeof ApiHomeyCallbackRoute
  ApiHomeyStartRoute: typeof ApiHomeyStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/var': {
      id: '/var'
      path: '/var'
      fullPath: '/var'
      preLoaderRoute: typeof VarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trening': {
      id: '/trening'
      path: '/trening'
      fullPath: '/trening'
      preLoaderRoute: typeof TreningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smarthus': {
      id: '/smarthus'
      path: '/smarthus'
      fullPath: '/smarthus'
      preLoaderRoute: typeof SmarthusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hytta': {
      id: '/hytta'
      path: '/hytta'
      fullPath: '/hytta'
      preLoaderRoute: typeof HyttaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hundene': {
      id: '/hundene'
      path: '/hundene'
      fullPath: '/hundene'
      preLoaderRoute: typeof HundeneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homey/start': {
      id: '/api/homey/start'
      path: '/api/homey/start'
      fullPath: '/api/homey/start'
      preLoaderRoute: typeof ApiHomeyStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homey/callback': {
      id: '/api/homey/callback'
      path: '/api/homey/callback'
      fullPath: '/api/homey/callback'
      preLoaderRoute: typeof ApiHomeyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  HundeneRoute: HundeneRoute,
  HyttaRoute: HyttaRoute,
  LoginRoute: LoginRoute,
  SmarthusRoute: SmarthusRoute,
  TreningRoute: TreningRoute,
  VarRoute: VarRoute,
  ApiHomeyCallbackRoute: ApiHomeyCallbackRoute,
  ApiHomeyStartRoute: ApiHomeyStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
